/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudyPlanRouteImport } from './routes/_authenticated/study-plan'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as AuthenticatedSessionsNewRouteImport } from './routes/_authenticated/sessions/new'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions/$sessionId'
import { Route as AuthenticatedMessagesThreadIdRouteImport } from './routes/_authenticated/messages/$threadId'
import { Route as AuthenticatedCommunitiesNewRouteImport } from './routes/_authenticated/communities/new'
import { Route as AuthenticatedCommunitiesSlugRouteImport } from './routes/_authenticated/communities/$slug'
import { Route as AuthenticatedSessionsSessionIdRoomRouteImport } from './routes/_authenticated/sessions/$sessionId.room'
import { Route as AuthenticatedSessionsSessionIdEditRouteImport } from './routes/_authenticated/sessions/$sessionId.edit'

const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudyPlanRoute = AuthenticatedStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsNewRoute =
  AuthenticatedSessionsNewRouteImport.update({
    id: '/sessions/new',
    path: '/sessions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesThreadIdRoute =
  AuthenticatedMessagesThreadIdRouteImport.update({
    id: '/messages/$threadId',
    path: '/messages/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunitiesNewRoute =
  AuthenticatedCommunitiesNewRouteImport.update({
    id: '/communities/new',
    path: '/communities/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunitiesSlugRoute =
  AuthenticatedCommunitiesSlugRouteImport.update({
    id: '/communities/$slug',
    path: '/communities/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsSessionIdRoomRoute =
  AuthenticatedSessionsSessionIdRoomRouteImport.update({
    id: '/room',
    path: '/room',
    getParentRoute: () => AuthenticatedSessionsSessionIdRoute,
  } as any)
const AuthenticatedSessionsSessionIdEditRoute =
  AuthenticatedSessionsSessionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/communities': typeof CommunitiesRoute
  '/explore': typeof ExploreRoute
  '/safety': typeof SafetyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/study-plan': typeof AuthenticatedStudyPlanRoute
  '/communities/$slug': typeof AuthenticatedCommunitiesSlugRoute
  '/communities/new': typeof AuthenticatedCommunitiesNewRoute
  '/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/sessions/$sessionId/edit': typeof AuthenticatedSessionsSessionIdEditRoute
  '/sessions/$sessionId/room': typeof AuthenticatedSessionsSessionIdRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/communities': typeof CommunitiesRoute
  '/explore': typeof ExploreRoute
  '/safety': typeof SafetyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/study-plan': typeof AuthenticatedStudyPlanRoute
  '/communities/$slug': typeof AuthenticatedCommunitiesSlugRoute
  '/communities/new': typeof AuthenticatedCommunitiesNewRoute
  '/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/sessions/$sessionId/edit': typeof AuthenticatedSessionsSessionIdEditRoute
  '/sessions/$sessionId/room': typeof AuthenticatedSessionsSessionIdRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/communities': typeof CommunitiesRoute
  '/explore': typeof ExploreRoute
  '/safety': typeof SafetyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/study-plan': typeof AuthenticatedStudyPlanRoute
  '/_authenticated/communities/$slug': typeof AuthenticatedCommunitiesSlugRoute
  '/_authenticated/communities/new': typeof AuthenticatedCommunitiesNewRoute
  '/_authenticated/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/_authenticated/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/sessions/$sessionId/edit': typeof AuthenticatedSessionsSessionIdEditRoute
  '/_authenticated/sessions/$sessionId/room': typeof AuthenticatedSessionsSessionIdRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/communities'
    | '/explore'
    | '/safety'
    | '/admin'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/study-plan'
    | '/communities/$slug'
    | '/communities/new'
    | '/messages/$threadId'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/users/$userId'
    | '/messages/'
    | '/sessions/$sessionId/edit'
    | '/sessions/$sessionId/room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/communities'
    | '/explore'
    | '/safety'
    | '/admin'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/study-plan'
    | '/communities/$slug'
    | '/communities/new'
    | '/messages/$threadId'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/users/$userId'
    | '/messages'
    | '/sessions/$sessionId/edit'
    | '/sessions/$sessionId/room'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/communities'
    | '/explore'
    | '/safety'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/study-plan'
    | '/_authenticated/communities/$slug'
    | '/_authenticated/communities/new'
    | '/_authenticated/messages/$threadId'
    | '/_authenticated/sessions/$sessionId'
    | '/_authenticated/sessions/new'
    | '/_authenticated/users/$userId'
    | '/_authenticated/messages/'
    | '/_authenticated/sessions/$sessionId/edit'
    | '/_authenticated/sessions/$sessionId/room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunitiesRoute: typeof CommunitiesRoute
  ExploreRoute: typeof ExploreRoute
  SafetyRoute: typeof SafetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/study-plan': {
      id: '/_authenticated/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof AuthenticatedStudyPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/new': {
      id: '/_authenticated/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AuthenticatedSessionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$threadId': {
      id: '/_authenticated/messages/$threadId'
      path: '/messages/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communities/new': {
      id: '/_authenticated/communities/new'
      path: '/communities/new'
      fullPath: '/communities/new'
      preLoaderRoute: typeof AuthenticatedCommunitiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communities/$slug': {
      id: '/_authenticated/communities/$slug'
      path: '/communities/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof AuthenticatedCommunitiesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId/room': {
      id: '/_authenticated/sessions/$sessionId/room'
      path: '/room'
      fullPath: '/sessions/$sessionId/room'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRoomRouteImport
      parentRoute: typeof AuthenticatedSessionsSessionIdRoute
    }
    '/_authenticated/sessions/$sessionId/edit': {
      id: '/_authenticated/sessions/$sessionId/edit'
      path: '/edit'
      fullPath: '/sessions/$sessionId/edit'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdEditRouteImport
      parentRoute: typeof AuthenticatedSessionsSessionIdRoute
    }
  }
}

interface AuthenticatedSessionsSessionIdRouteChildren {
  AuthenticatedSessionsSessionIdEditRoute: typeof AuthenticatedSessionsSessionIdEditRoute
  AuthenticatedSessionsSessionIdRoomRoute: typeof AuthenticatedSessionsSessionIdRoomRoute
}

const AuthenticatedSessionsSessionIdRouteChildren: AuthenticatedSessionsSessionIdRouteChildren =
  {
    AuthenticatedSessionsSessionIdEditRoute:
      AuthenticatedSessionsSessionIdEditRoute,
    AuthenticatedSessionsSessionIdRoomRoute:
      AuthenticatedSessionsSessionIdRoomRoute,
  }

const AuthenticatedSessionsSessionIdRouteWithChildren =
  AuthenticatedSessionsSessionIdRoute._addFileChildren(
    AuthenticatedSessionsSessionIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedStudyPlanRoute: typeof AuthenticatedStudyPlanRoute
  AuthenticatedCommunitiesSlugRoute: typeof AuthenticatedCommunitiesSlugRoute
  AuthenticatedCommunitiesNewRoute: typeof AuthenticatedCommunitiesNewRoute
  AuthenticatedMessagesThreadIdRoute: typeof AuthenticatedMessagesThreadIdRoute
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRouteWithChildren
  AuthenticatedSessionsNewRoute: typeof AuthenticatedSessionsNewRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedStudyPlanRoute: AuthenticatedStudyPlanRoute,
  AuthenticatedCommunitiesSlugRoute: AuthenticatedCommunitiesSlugRoute,
  AuthenticatedCommunitiesNewRoute: AuthenticatedCommunitiesNewRoute,
  AuthenticatedMessagesThreadIdRoute: AuthenticatedMessagesThreadIdRoute,
  AuthenticatedSessionsSessionIdRoute:
    AuthenticatedSessionsSessionIdRouteWithChildren,
  AuthenticatedSessionsNewRoute: AuthenticatedSessionsNewRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunitiesRoute: CommunitiesRoute,
  ExploreRoute: ExploreRoute,
  SafetyRoute: SafetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
